fetched = 2023-10-12T18:24:09Z

[[member]]
id        = "support@workos.com"
name      = "WorkOS"
pledge    = 400
platforms = ["github"]

[[member]]
id        = "tiensonqin@gmail.com"
name      = "Tienson Qin"
pledge    = 100
platforms = ["github"]

[[member]]
id        = "robbert@frameless.io"
name      = "Robbert Broersma, Frameless B.V."
pledge    = 100
platforms = ["patreon"]

[[member]]
id        = "chris@oakmac.com"
name      = "Chris Oakman"
pledge    = 54
platforms = ["github", "patreon"]

[[member]]
id        = "vitali.pe@gmail.com"
name      = "Vitali Perchonok"
pledge    = 50
platforms = ["patreon"]

[[member]]
id        = "forro.zalan@gmail.com"
name      = "Zalán Forró"
pledge    = 50
platforms = ["patreon"]

[[member]]
id        = "dustin@hyperfiddle.net"
name      = "Dustin Getz"
pledge    = 50
platforms = ["patreon"]

[[member]]
id        = "chris.smothers@gmail.com"
name      = "Chris Smothers"
pledge    = 15
platforms = ["github", "patreon"]

[[member]]
id        = "soren@zoren.dk"
name      = "Søren Sjørup"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "sasha.savchenko@gmail.com"
name      = "Alexander Savchenko"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "rgdelato@gmail.com"
name      = "Ryan"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "public@rafaelferreira.net"
name      = "Rafael de F. Ferreira"
pledge    = 10
platforms = ["github"]

[[member]]
id        = "oss@fingerprint.com"
name      = "Fingerprint"
pledge    = 10
platforms = ["github"]

[[member]]
id        = "nlhepler@gmail.com"
name      = "L. H."
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "luke@vanderhart.net"
name      = "Luke VanderHart"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "lexi.lambda@gmail.com"
name      = "Alexis King"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "kevin@keminglabs.com"
name      = "Kevin Lynagh"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "kap4020@gmail.com"
name      = "the-alchemist"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "devgru@mail.ru"
name      = "Dmitriy Semyushkin"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "cloutiertyler@gmail.com"
name      = "Tyler Cloutier"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "bravit111@gmail.com"
name      = "Vitaly Bragilevsky"
pledge    = 10
platforms = ["patreon"]

[[member]]
id        = "aabur@mail.ru"
name      = "Alexander Burchenko"
pledge    = 10
platforms = ["github"]

[[member]]
id        = "donald.ball@gmail.com"
name      = "Donald Ball"
pledge    = 8
platforms = ["patreon"]

[[member]]
id        = "yuri.zemlyanskiy@gmail.com"
name      = "Yura Zemlyanskiy"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "ultimatedood@gmail.com"
name      = "059"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "tulir"
name      = "Tulir Asokan"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "tojoko@gmail.com"
name      = "Tomi Joki-Korpela"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "terje@ceteo.no"
name      = "Terje Sten Bjerkseth"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "slowdownitsfine"
name      = "slowdownitsfine"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "sergey.senchilo@gmail.com"
name      = "Сергей Сенчило"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "seanjensengrey"
name      = "Sean Jensen-Grey"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "sam.taylor@me.com"
name      = "Sammy Taylor"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "mchlggr"
name      = "Michael Geiger"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "kanumaiku@gmail.com"
name      = "Ikuru Kanuma"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "jdf-id-au"
name      = "Jeremy Field"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "ilya.razenshteyn@gmail.com"
name      = "Ilya Razenshteyn"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "hellomind@gmail.com"
name      = "Sergey Serebryakov"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "filipesilva"
name      = "Filipe Silva"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "dwt@outlook.com"
name      = "Dave Thompson"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "drew.verlee@gmail.com"
name      = "drew verlee"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "djwhitt@gmail.com"
name      = "David Whittington"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "dfm@razorwind.org"
name      = "Dan Martinez"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "david.nachman.09@gmail.com"
name      = "David Nachman"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "brightcor@gmail.com"
name      = "Александр Шепелин"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "brandon.r.walters@gmail.com"
name      = "Brandon Walters"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "ben@bbrinck.com"
name      = "Ben Brinckerhoff"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "arnoesterhuizen"
name      = "Arno Esterhuizen"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "ambrose@ambrosebs.com"
name      = "Ambrose Bonnaire-Sergeant"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "adam@getstrake.com"
name      = "A. R. Younce"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "Xanewok@gmail.com"
name      = "Igor Matuszewski"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "ToQceEqaKcF@pm.me"
name      = "Konstantin Telnoy"
pledge    = 5
platforms = ["patreon"]

[[member]]
id        = "92.peter.szalai@gmail.com"
name      = "Peter Szalai"
pledge    = 5
platforms = ["github"]

[[member]]
id        = "twh@pobox.com"
name      = "Thomas W. Holt Jr."
pledge    = 4
platforms = ["patreon"]

[[member]]
id        = "folcon@gmail.com"
name      = "Niluka Satharasinghe"
pledge    = 4
platforms = ["patreon"]

[[member]]
id        = "dieter@komendera.com"
name      = "Dieter Komendera"
pledge    = 4
platforms = ["patreon"]

[[member]]
id        = "can@lispy.io"
name      = "Christos Anagnostakis"
pledge    = 4
platforms = ["patreon"]

[[member]]
id        = "emmaly@emma.ly"
name      = "Emmaly"
pledge    = 3
platforms = ["github", "patreon"]

[[member]]
id        = "zero13cool@yandex.com"
name      = "Vladimir Savin"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "zaki@manian.org"
name      = "Zaki"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "zacharymoring@gmail.com"
name      = "zed"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "troggy"
name      = "Kosta Korenkov"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "swhiteman"
name      = "swhiteman"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "raphael.saunier@gmail.com"
name      = "Raphaël Saunier"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "patreon@drowsy.de"
name      = "Albrecht Schmidt"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "p.e.strickland@gmail.com"
name      = "Paul Strickland"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "nimareq@gmail.com"
name      = "Vitezslav Ackermann Ferko"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "nigelharsch@gmail.com"
name      = "nigel"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "n.jeker@gmx.net"
name      = "Nicolas Jeker"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "me@mitrich.me"
name      = "Dmitry Kolosov"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "lumaxis"
name      = "Lukas Spieß"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "konradszydlo"
name      = "Konrad Szydlo"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "koluch@koluch.ru"
name      = "Nikolai Mavrenkov"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "jgoodhcg@gmail.com"
name      = "jgoodhcg"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "jeff@jmetzner.com"
name      = "Jeff Metzner"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "jake@jakehoward.org"
name      = "Jake"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "jacob@mischka.me"
name      = "Jacob Mischka"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "fravia190@gmail.com"
name      = "Yaroslav T."
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "drackett@mac.com"
name      = "Chris"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "dp.egan@dpegan.com"
name      = "Daniel P. Egan"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "daniel@kraus.my"
name      = "Daniel Kraus"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "d@petranek.net"
name      = "Daniel Petranek"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "clark@countable.ca"
name      = "Clark Van Oyen"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "christopher.andrew.kwiatkowski@gmail.com"
name      = "Chris Kwiatkowski"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "brian@brianhurlow.com"
name      = "Brian Hurlow"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "artkh90@gmail.com"
name      = "Artem Khatchatourov"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "alexandre_mutel@live.com"
name      = "Alexandre Mutel"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "adam@adamfrey.me"
name      = "Adam Frey"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "MatyasKriz"
name      = "Matty Cross"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "Jasondebo@gmail.com"
name      = "Jason Dubaniewicz"
pledge    = 2
platforms = ["patreon"]

[[member]]
id        = "Binkus"
name      = "M. F. W. Bink"
pledge    = 2
platforms = ["github"]

[[member]]
id        = "zoe@zgagnon.com"
name      = "Zoe"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "wraithofnine@gmail.com"
name      = "Joshua Mitchell"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "vikky49@gmail.com"
name      = "Pratyush M"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "tim.t.walker@outlook.com"
name      = "Tim Walker"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "sergeyev.anton.s@gmail.com"
name      = "Anton"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "rob@neverwood.org"
name      = "Rob Napier"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "pjagielski@o2.pl"
name      = "Piotr Jagielski"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "nothingisbad@gmail.com"
name      = "Ryan Domigan"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "nicholasafarley@gmail.com"
name      = "Nicholas Farley"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "mashehu3@gmail.com"
name      = "Mashehu"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "malte@sandstede.com"
name      = "Malte Sandstede"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "luciano.maiwald@mailbox.org"
name      = "Luciano Maiwald"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "lair@hawke.ru"
name      = "Sergei Rogovtcev"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "jrgroup.learning@gmail.com"
name      = "Peterson Onyeukwu"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "internetbidon@gmail.com"
name      = "GodOf"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "gor.martsen@gmail.com"
name      = "Gor Martsen"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "gmiggs@gmail.com"
name      = "Miguel Bermudez"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "fdh4@aol.com"
name      = "Frank Howard"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "dr.akulavich@gmail.com"
name      = "Anton Yakutovich"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "deleter8@gmail.com"
name      = "deleter"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "daniel@danielcloud.org"
name      = "Daniel Cloud"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "cmt.miniBill@gmail.com"
name      = "Leonardo Taglialegne"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "ben@doodle.co.uk"
name      = "Ben Duguid"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "avi@aviflax.com"
name      = "Avi Flax"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "austin@finlinson.net"
name      = "Austin Finlinson"
pledge    = 1
platforms = ["patreon"]

[[member]]
id        = "alex.shulgin@gmail.com"
name      = "Alex Shulgin"
pledge    = 1
platforms = ["patreon"]

